export const DIETARY_OPTIONS = [
  'Vegetarian',
  'Vegan',
  'Halal',
  'Gluten-Free',
  'Dairy-Free',
  'Nut-Free',
  'Keto',
  'Organic',
] as const;

export type DietaryPreference = typeof DIETARY_OPTIONS[number];

export const CATEGORIES_LIST = [
  { key: 'ALL', label: 'All', iconName: 'grid' },
  { key: 'BREAKFAST', label: 'Breakfast', iconName: 'coffee' },
  { key: 'LUNCH', label: 'Lunch', iconName: 'sun' },
  { key: 'DINNER', label: 'Dinner', iconName: 'moon' },
  { key: 'SNACKS', label: 'Snacks', iconName: 'pie-chart' },
  { key: 'COMBO', label: 'Combos', iconName: 'gift' },
] as const;

export interface DistrictTownMap {
  [district: string]: string[];
}

export const DISTRICT_TOWN_DATA: DistrictTownMap = {
  Colombo: [
    'Colombo 01 (Fort)',
    'Colombo 02 (Slave Island)',
    'Colombo 03 (Colpetty)',
    'Colombo 04 (Bambalapitiya)',
    'Colombo 05 (Havelock Town)',
    'Colombo 06 (Wellawatte)',
    'Colombo 07 (Cinnamon Gardens)',
    'Colombo 08 (Borella)',
    'Colombo 09 (Dematagoda)',
    'Colombo 10 (Maradana)',
    'Colombo 11 (Pettah)',
    'Colombo 12 (Kochchikade)',
    'Colombo 13 (Kotahena)',
    'Colombo 14 (Grandpass)',
    'Colombo 15 (Modara)',
    'Dehiwala',
    'Mount Lavinia',
    'Nugegoda',
    'Maharagama',
    'Battaramulla',
    'Rajagiriya',
    'Kotte',
    'Kaduwela',
    'Malabe',
    'Homagama',
    'Piliyandala',
    'Moratuwa',
  ],
  Gampaha: [
    'Gampaha',
    'Negombo',
    'Wattala',
    'Ja-Ela',
    'Kiribathgoda',
    'Kelaniya',
    'Kadawatha',
    'Nittambuwa',
    'Minuwangoda',
    'Ragama',
    'Mirigama',
  ],
  Kalutara: [
    'Kalutara',
    'Panadura',
    'Horana',
    'Beruwala',
    'Aluthgama',
    'Matugama',
    'Wadduwa',
  ],
  Kandy: [
    'Kandy City',
    'Peradeniya',
    'Katugastota',
    'Gampola',
    'Kundasale',
    'Digana',
    'Akurana',
    'Nawalapitiya',
  ],
  Galle: [
    'Galle Fort',
    'Galle City',
    'Hikkaduwa',
    'Unawatuna',
    'Karapitiya',
    'Ambalangoda',
    'Elpitiya',
    'Bentota',
  ],
  Matara: [
    'Matara City',
    'Mirissa',
    'Weligama',
    'Dikwella',
    'Akuressa',
    'Kamburupitiya',
  ],
  Jaffna: [
    'Jaffna City',
    'Nallur',
    'Chavakachcheri',
    'Point Pedro',
    'Karainagar',
    'Chunnakam',
  ],
  Kurunegala: [
    'Kurunegala City',
    'Kuliyapitiya',
    'Pannala',
    'Narammala',
    'Maho',
    'Giriulla',
  ],
  Anuradhapura: [
    'Anuradhapura City',
    'Kekirawa',
    'Eppawala',
    'Medawachchiya',
    'Habarana',
  ],
  Badulla: [
    'Badulla City',
    'Bandarawela',
    'Ella',
    'Diyatalawa',
    'Hali-Ela',
    'Welimada',
  ],
  NuwaraEliya: [
    'Nuwara Eliya',
    'Hatton',
    'Nanu Oya',
    'Talawakele',
    'Ragala',
  ],
  Ratnapura: [
    'Ratnapura City',
    'Balangoda',
    'Embilipitiya',
    'Eheliyagoda',
    'Kuruwita',
  ],
};
